image: java:8-jdk

stages:
  - build
  - deploy
  
before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=/cache/.gradle

build:
  stage: build
  script:
    - "echo \"\nsigning.keyId=$GPG_KEY_ID\" >> gradle.properties"
    - "echo \"\nsigning.password=$GPG_PASSPHRASE\" >> gradle.properties"
    - "echo \"\nsigning.secretKeyRingFile=$GPG_KEY_RING_FILE\" >> gradle.properties"
    - "echo \"$GPG_KEY_RING_FILE\" > /tmp/key"
    - "gpg --import /tmp/key"
    - ./gradlew build
  only:
    variables:
       - $BUILD_MAVEN != "publish"
  artifacts:
    paths:
      - build/libs/
    
deploy:
  stage: deploy
  script:
    - ./gradlew build publish
  only:
    variables:
        - $BUILD_MAVEN == "publish"