image: java:8-jdk

stages:
  - build
  - deploy
  
before_script:
  - chmod +x gradlew
  - echo $GPG_KEY_RING_FILE | base64 -d > /tmp/key
  - echo $JAVA_KEY_FILE | base64 -d > /tmp/key2
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - echo "signing.keyId=$GPG_KEY_ID" >> gradle.properties
    - echo "signing.password=$GPG_PASSPHRASE" >> gradle.properties
    - echo "signing.secretKeyRingFile=/tmp/key" >> gradle.properties
    - echo "signing.keystorePath=/tmp/key2" >> gradle.properties
    - ./gradlew build --stacktrace
  only:
    variables:
       - $BUILD_MAVEN != "publish"
  artifacts:
    paths:
      - build/libs/
    
deploy:
  stage: deploy
  script:
    - ./gradlew build publish
  only:
    variables:
        - $BUILD_MAVEN == "publish"